### ISSUE TITLE
Accumulation of gradient and Hessian

### ISSUE THREAD

**Issue by githubharald** [davda54/ada-hessian#3]
Hi,

I tried the "Advanced usage" example code you showed in your README to accumulate multiple Hessians. I did this by calling set_hessian() multiple times for the same input to get a better estimate for the Hessian (see paper formula 11). However, the estimate got worse when increasing the number of samples.

It seems like the gradient is accumulated, but the individual Hessian estimates are computed from the so-far accumulated gradients instead of just the most rescent added gradient. Say we have gradients g1, g2, g3. The Hessian-vector product estimates should be computed using g1 to get H1, g2 to get H2 and g3 to get H3, but instead, they are computed from g1, (g1+g2), (g1+g2+g3).

So, coming back to my original example, where I have g1=g2=g3 (because of same input), the Hessian is by a factor of (1+2+3) too large, and if I divide the Hessian by this value, the result is as expected.
An example where this is good to see is something like f(x,y)=x^2+y^2 with betas=(0, 0) and lr=1, where the optimizer should jump directly to the minimum, however, without the mentioned correction it needs multiple steps.

**Comment by davda54** [comment]
Hi, you are absolutely right. While correct accumulation could be supported, it seems that it would make the code much more complicated and it would require more memory (for storing both <img src="https://render.githubusercontent.com/render/math?math=\mathbf{g}_i"> and <img src="https://render.githubusercontent.com/render/math?math=\sum{\mathbf{g}_i}">), so I'll completely remove this feature in the next version. It doesn't seem to be worth it for the default (more common) simple usage.

On the other hand, better approximation of formula 11 doesn't seem to need accumulated gradients, all samples of <img src="https://render.githubusercontent.com/render/math?math=\mathbf{H}z"> should be computed from the same gradient. I'll add an option to use more samples :)

**Comment by githubharald** [comment]
Yes, I also did it that way: simply pass number of samples to set_hessian(num_samples),  accumulate z*(H@z) values, and finally divide by that number. But good to know that this will be in the next release :-)

**Comment by githubharald** [comment]
works now, thank you :+1:  
I open-sourced my code for experimenting with AdaHessian where I used your optimizer implementation (of course added copyright + link to your repo).

**Comment by davda54** [comment]
That's amazing, thank you for sharing the experiments!
